### ISSUE TITLE
jupyterlab_nengo -> jupyterlab-nengo

### ISSUE THREAD

**Issue by tbekolay** [nengo/jupyterlab_nengo#1]
Could you rename this repo and update the appropriate references to `jupyterlab-nengo`?

**Comment by jgosmann** [comment]
For sure, it seemed to me that the underscore notation is standard for JupyterLab extensions (examples: [1](https://github.com/jupyterlab/extension-cookiecutter-ts/blob/master/cookiecutter.json#L3), [2](https://github.com/gnestor/jupyterlab_table), [3](https://github.com/jupyterlab/jupyterlab_app), [4](https://github.com/jupyterlab/jupyterlab_xkcd), [5](https://github.com/bokeh/jupyterlab_bokeh)) and they are published on/installed with npm, not pip. But turns out there is also a number of extensions using the hyphen notation ([1](https://github.com/jupyterlab/jupyterlab-monaco), [2](https://github.com/jupyterlab/jupyter-renderers), [3](https://github.com/jupyterlab/jupyterlab-google-drive), [4](https://github.com/jupyterlab/jupyterlab-github), [5](https://github.com/jupyterlab/jupyterlab-latex)).
